use inkless_core::grapheme::gph;
use inkless_macros::gph;

pub const DIGIT_COUNT: usize = 36;

pub static MINUS: &'static gph = gph!("-");

pub static DIGITS_UPPER: [&'static gph; DIGIT_COUNT] = [
    gph!("0"),
    gph!("1"),
    gph!("2"),
    gph!("3"),
    gph!("4"),
    gph!("5"),
    gph!("6"),
    gph!("7"),
    gph!("8"),
    gph!("9"),
    gph!("A"),
    gph!("B"),
    gph!("C"),
    gph!("D"),
    gph!("E"),
    gph!("F"),
    gph!("G"),
    gph!("H"),
    gph!("I"),
    gph!("J"),
    gph!("K"),
    gph!("L"),
    gph!("M"),
    gph!("N"),
    gph!("O"),
    gph!("P"),
    gph!("Q"),
    gph!("R"),
    gph!("S"),
    gph!("T"),
    gph!("U"),
    gph!("V"),
    gph!("W"),
    gph!("X"),
    gph!("Y"),
    gph!("Z"),
];

pub static DIGITS_LOWER: [&'static gph; DIGIT_COUNT] = [
    gph!("0"),
    gph!("1"),
    gph!("2"),
    gph!("3"),
    gph!("4"),
    gph!("5"),
    gph!("6"),
    gph!("7"),
    gph!("8"),
    gph!("9"),
    gph!("a"),
    gph!("b"),
    gph!("c"),
    gph!("d"),
    gph!("e"),
    gph!("f"),
    gph!("g"),
    gph!("h"),
    gph!("i"),
    gph!("j"),
    gph!("k"),
    gph!("l"),
    gph!("m"),
    gph!("n"),
    gph!("o"),
    gph!("p"),
    gph!("q"),
    gph!("r"),
    gph!("s"),
    gph!("t"),
    gph!("u"),
    gph!("v"),
    gph!("w"),
    gph!("x"),
    gph!("y"),
    gph!("z"),
];
